title: iChing
description: Interactive iChing
baseurl: "/iching" # the subpath of your site, e.g. /blog
url: "https://quilime.github.io/iching" # the base hostname & protocol for your site, e.g. http://example.com
keyboard: "Keyboard" # keyboard sourcefiles location

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
